close all;
format short;

filename = sprintf(strcat("F:\\tempo sim data\\224Gbpers_DP-16QAM\\", ...
                           num2str(BitRate/1e9),"Gbpers_", ...
                           num2str(SymbolRate/1e9),"GBaud_DP-16QAM_", ...
                           num2str(Samplesperbit),"Saperb_", ...
                           num2str(OSNR),"dB_", ...
                           num2str(SignalPower),"dBm_", ...
                           num2str(rolloff), ...
                           "_%s.mat"),datestr(now,"mmmmddyyyyHHMMSSFFF") ...
                    );
save(filename,'-v7.3')